# =============================================================================
# Source : Ansible for Junos OS Developer Guide
# Section: Use Ansible to Configure Junos Devices
#          > How to Load Configuration Data from a Local or Remote File
#          > Local File (src)
# Page   : 170
# URL    : https://www.juniper.net/documentation/us/en/software/junos-ansible/
#          ansible/topics/topic-map/junos-ansible-configuration-loading-committing.html
# -----------------------------------------------------------------------------
# Description:
#   Loads configuration data from a file on the Ansible control node using
#   the src argument and commits. {{ inventory_hostname }} allows per-device
#   configuration files.
#
# Usage:
#   ansible-playbook config_load_local_file.yml -i <inventory>
# =============================================================================
---
- name: "Load and commit configuration"
  hosts: dc1
  connection: local
  gather_facts: no


  tasks:
    - name: "Load configuration from a local file and commit"
      juniper.device.config:
         load: "merge"
         src: "build_conf/{{ inventory_hostname }}/junos.conf"
      register: response
    - name: "Print the response"
      ansible.builtin.debug:
         var: response
